CREATE TABLE Usuario
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Perfil INT NOT NULL,
    Login VARCHAR(150) NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    DataCadastro DATETIME NOT NULL DEFAULT GETDATE()
);